### ISSUE TITLE
Problem of robot visualization

### ISSUE THREAD

**Issue by RoboticsZhang** [ami-iit/paper_lerario_2022_humanoids_planning-multimodal-locomotion#4]
Dear Giulero, thank you for the code open-sourcing and the detailed documentations!
I found some problems of robot visualization. By following your installation guides, I successfully ran your simulation environment(including the optimization codes in the runs/ directory), but the robot mesh files could not be loaded. The terminal output is as follows:
`Robot loaded.
Irrlicht Engine version 1.8.5
Linux 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64
Using renderer: OpenGL 4.6.0
NVIDIA TITAN X (Pascal)/PCIe/SSE2: NVIDIA Corporation
OpenGL driver version is 1.2 or better.
GLSL version: 4.6
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_root_link_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_root_link_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_hip_1_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_hip_1_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_lap_belt_1_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_lap_belt_1_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_hip_1_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_hip_1_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_hip_2_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_hip_2_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_upper_thigh_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_upper_thigh_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_thigh_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_thigh_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_shank_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_shank_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_ankle_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_ankle_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_foot_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_foot_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_sole_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_sole_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_lap_belt_2_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_lap_belt_2_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_chest_bb_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_chest_bb_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_neck_1_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_neck_1_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_p220_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_p220_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_chest_aruco_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_chest_aruco_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_p220_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_p220_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_neck_2_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_neck_2_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_head_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_head_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_shoulder_1_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_shoulder_1_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_shoulder_1_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_shoulder_1_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_shoulder_2_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_shoulder_2_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_upper_arm_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_upper_arm_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_elbow_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_elbow_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_elbow_prosup_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_elbow_prosup_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_elbow_p160_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_r_elbow_p160_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_shoulder_2_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_shoulder_2_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_upper_arm_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_upper_arm_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_elbow_prt.obj
Error in loading mesh /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_elbow_prt.obj
Could not load mesh, file format seems to be unsupported: /home/ruibin/zrb_ws/ironcub_tabv/ironcub_software/models//iRonCub-Mk1_1/iRonCub/meshes/obj/sim_sea_2-5_l_elbow_prosup_prt.obj
`
Note that the mesh files are founded (I have set the GAZEBO_MODEL_PATH, etc.), but cannot be loaded because "file format seems to be unsupported:". Have you encountered similar situations before? Do I miss some dependencies? Thank you.

**Comment by RoboticsZhang** [comment]
Is robot visualization achieved by the iDynTree package? I have installed iDynTree==8.1.0 as required.

**Comment by traversaro** [comment]
Hello @RoboticsZhang ! I am afraid that you did not downloaded ironcub-software with Git LFS enabled, can you try to enable git lfs and clone again ironcub-software?

**Comment by RoboticsZhang** [comment]
It works! Thank you very much @traversaro! I will close the issue.

**Comment by traversaro** [comment]
@Giulero do you think we can add a reference to LFS in https://github.com/ami-iit/paper_lerario_2022_humanoids_planning-multimodal-locomotion#code ? I guess this can be quite a common error.

**Comment by Giulero** [comment]
Thanks @RoboticsZhang for opening the issue! :)
Thanks @traversaro for solving it :) 
> do you think we can add a reference to LFS in https://github.com/ami-iit/paper_lerario_2022_humanoids_planning-multimodal-locomotion#code ? I guess this can be quite a common error.

Sure, it makes sense!
